backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

display_url: https://gatsby-netlify-cms-example.netlify.com/

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Main Image",
              name: "mainImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Image Gallery",
              name: "gallery",
              widget: "list",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/pastMeetups/index.md"
        label: "Past Meetups"
        name: "pastMeetups"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "past-meetups-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - { 
              label: "Main Image Text", 
              name: "mainImageText", 
              widget: "object",
              fields: [
                {label: "Item Text One", name: "itemTextOne", widget: "string"},
                {label: "Item Text Two", name: "itemTextTwo", widget: "string"},
                {label: "Item Text Three", name: "itemTextThree", widget: "string"},
                {label: "Item Text Four", name: "itemTextFour", widget: "string"}
              ],
            }
          - { 
              label: "Section Welcome",
              name: "sectionWelcome",
              widget: "object",
              fields: [
                { label: "Title", name: "title", widget: "string" },
                { label: "Body", name: "body", widget: "markdown" },
                { label: "Image", name: "image", widget: "image" },
                { label: "Image Description", name: "imageAlt", widget: "string" },
                { label: "Quote", name: "quote", widget: "string" },
                { label: "Highlighted Text", name: "highlightedText", widget: "string"}
              ]
            }
          - {
              label: "Section Schedule",
              name: "sectionSchedule",
              widget: "object",
              fields: [
                { label: "Title", name: "title", widget: "string" },
                { 
                  label: "Classes Timetable", 
                  name: "classesTimetable", 
                  widget: "object",
                  fields: [
                    { label: "Sub Heading", name: "subHeading", widget: "string" },
                    { label: "Body", name: "body", widget: "markdown" }
                  ] 
                },
                { 
                  label: "Workshop Schedule", 
                  name: "workshopSchedule", 
                  widget: "object",
                  fields: [
                    { label: "Sub Heading", name: "subHeading", widget: "string" },
                    { label: "Body", name: "body", widget: "markdown" }
                  ] 
                },
                { 
                  label: "Event Schedule", 
                  name: "eventSchedule", 
                  widget: "object",
                  fields: [
                    { label: "Sub Heading", name: "subHeading", widget: "string" },
                    { label: "Body", name: "body", widget: "markdown" }
                  ] 
                }
              ]
            }
          - {
              label: "Section My Story",
              name: "sectionMyStory",
              widget: "object",
              fields: [
                { label: "Title", name: "title", widget: "string" },
                { label: "Body", name: "body", widget: "markdown" }
              ]
            }
          - {
              label: "Section Connect",
              name: "sectionConnect",
              widget: "object",
              fields: [
                { label: "Title", name: "title", widget: "string" },
                { 
                  label: "Contact", 
                  name: "contact", 
                  widget: "list", 
                  fields: [
                    { label: "Sub Heading", name: "subHeading", widget: "string" },
                    { label: "Link URL", name: "linkURL", widget: "string" }
                  ]
                },
                {
                  label: "Services", 
                  name: "services", 
                  widget: "object", 
                  fields: [
                    { label: "Title", name: "title", widget: "string" },
                    { label: "Body", name: "body", widget: "markdown" }
                  ]
                },
                {
                  label: "Subscribe", 
                  name: "subscribe", 
                  widget: "object", 
                  fields: [
                    { label: "Title", name: "title", widget: "string" },
                    { label: "Body", name: "body", widget: "markdown" }
                  ]
                },
              ]
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/classes/index.md"
        label: "Classes"
        name: "classes"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "classes-page" }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Main Image",
              name: "mainImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/teaching/index.md"
        label: "Teachings"
        name: "teachings"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "teaching-page" }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Main Image",
              name: "mainImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
  - name: "navbarAndFooter"
    label: "Navbar & Footer"
    files:
      - file: "src/pages/navbar/index.md"
        label: "Navbar"
        name: "navbar"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "navbar" }
          - {
              label: "Menu Items",
              name: "menuItems",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link Type", name: "linkType", widget: "select", options: ["internal", "external", "hash"] },
                  { label: "Link URL", name: "linkURL", widget: "string", hint: "Use a relative URL (e.g. /about) if the link is an internal link." },
                ],
            }
          - {
              label: "Social Items",
              name: "socialLinks",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Social Type", name: "type", widget: string },
                  { label: "Social Link", name: "linkURL", widget: string },
                  { label: "Social Title", name: "hiddenText", widget: string }
                ],
            }
      - file: "src/pages/footer/index.md"
        label: "Footer"
        name: "footer"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "footer" }
          - { label: "Copyright Copy", name: "copyrightText", widget: "string"}
          - {
              label: "Logo Image & Tagline",
              name: "logoImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                  { label: "ImageLink", name: "imageLink", widget: "string"}
                ],
            }